//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleWebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student_Details_Registration
    {
        public string username { get; set; }
        public string password { get; set; }
        public string First_Name { get; set; }
        public string Last_Name { get; set; }
        public Nullable<System.DateTime> Date_of_Birth { get; set; }
        public string Location { get; set; }
        public string Degree { get; set; }
        public string Stream { get; set; }
    }
}
