//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoBoWebApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admin_Dashboard
    {
        public int S_No { get; set; }
        public string Hotel { get; set; }
        public System.DateTime Arrival { get; set; }
        public System.DateTime Departure { get; set; }
        public string Type { get; set; }
        public int Guests { get; set; }
        public decimal Price { get; set; }
    }
}
